### ISSUE TITLE
Great video!

### ISSUE THREAD

**Issue by benlimpic** [learn-co-curriculum/phase-1-lecture-videos-asynchronous-javascript-and-fetch#1]
### Canvas Link

https://learning.flatironschool.com/courses/5171/pages/video-asynchronous-javascript-and-fetch?module_item_id=375934

### Concern

no concern! I enjoyed and learned a lot here!

### Additional Context

I loved this!

### Suggested Changes

Very good explanation of how fetch and then help us communicate with the server : )

**Comment by graciemcguire** [comment]
Hey @benlimpic !
Thanks for the feedback, communicating with the server can be a tough concept to learn, and @ixnp really did an amazing job here. 
Happy Coding! 💙
